#!/bin/bash
dotnet publish --framework=netstandard2.0 --runtime=ubuntu-x64 /media/data/PhyNetFlow.OMNeT/PhyNetFlow.OMNeT
#cp ~/.nuget/packages/system.collections.immutable/1.4.0/lib/netstandard2.0/System.Collections.Immutable.dll /media/data/PhyNetFlow.OMNeT/PhyNetFlow.OMNeT/bin/Debug/netcoreapp2.0/ubuntu-x64/publish
cp -f /media/data/PhyNetFlow.OMNeT/PhyNetFlow.OMNeT/bin/Debug/netstandard2.0/ubuntu-x64/publish/* /media/data/inet_phynode/inet/examples/phynettest_mono
